gestor/urls.py
from django.urls import path,include
from Usuarios import views

urlpatterns = [
    ######Maneja el inicio de sesion
    path('accounts/', include('django.contrib.auth.urls')),
    #####
   
    path('', views.login, name='login'),
    #Modulo Parking
    path('estacionamiento/<str:token>/', views.estacionamiento, name='estacionamiento'),
    path('estacionamiento/<str:token>/Datos', views.listaautos, name='lista'),
    path('eliminarautosf/<str:patente>',views.eliminarautosf),
    path('editarautosf/<str:patente>',views.editarautosf),


    #Url Administracion
    path('administracion/<str:token>/', views.administracion, name='administracion'),
    path('administracion/<str:token>/Datos', views.listaperso, name='lista.perso'),
    path('eliminarpersonasf/<str:rut>',views.eliminarpersof),
    path('editarpersonasf/<str:rut>',views.editarpersof),
    #Url admin
    path('admin/<str:token>/', views.admin, name='admin'),
    path('solicitud/', views.solicitud, name='solicitud'),
    path('admin/<str:token>/Datos', views.listaadperso, name='persoad'),
    path('editarpersonasadf/<str:rut>',views.editarpersadof),
    path('eliminarpersonasadf/<str:rut>',views.eliminarpersadof),


    path('admin/<str:token>/Datos1', views.listaautos, name='autoad'),

    path('admin/<str:token>/signup/', views.signup, name='signup'),
    path('eliminarpersonas/<str:username>',views.eliminarpersonas),
    path('editarpersonas/<str:username>',views.editarpersonas),
    path('admin/<str:token>/signup/Datos2', views.listaadpersonas, name='pers'),


    path('admin/<str:token>/Datos3', views.listasoli, name='cosa'),
    path('eliminarsol/<str:rut>',views.eliminarsoli),
]

Usuarios/models.py
from django.db import models

class Usuario(models.Model):
    TIPO_USUARIO_CHOICES = [
    ('estacionamiento', 'estacionamiento'),
    ('administracion', 'administracion'),
    ('administrador', 'administrador'),
    ]
    username = models.CharField(max_length=50, unique=True)
    password = models.CharField(max_length=100)
    tipo = models.CharField(max_length=20,choices=TIPO_USUARIO_CHOICES)  

    class Meta:
        db_table = 'Trabajadores'


class Solicitud(models.Model):

    rut= models.CharField(max_length=50, unique=True)
    nueva= models.CharField(max_length=100)


    class Meta:
        db_table = 'Solicitud'
    

class Estacionamiento(models.Model):
    TIPO_USUARIO_CHOICES = [
        ('Visita', 'Visita'),
        ('Residente', 'Residente'),
        ('Externo', 'Externo'),
    ]

    patente = models.CharField(max_length=20, primary_key=True)
    modelo_auto = models.CharField(max_length=50)
    lugar = models.CharField(max_length=20)
    nombre_usuario_id = models.CharField(max_length=50)
    tipo_usuario = models.CharField(max_length=20, choices=TIPO_USUARIO_CHOICES)
    contacto = models.CharField(max_length=20)

    class Meta:
        db_table = 'Estacionaminto'
        

class Administracion(models.Model):
    TIPO_USUARIO_CHOICES = [
        ('Visita', 'Visita'),
        ('Residente', 'Residente'),
        ('Externo', 'Externo'),
    ]

    rut = models.CharField(max_length=20, primary_key=True)
    habitacion = models.CharField(max_length=50)
    nombre_usuario_id = models.CharField(max_length=50)
    tipo_usuario = models.CharField(max_length=20, choices=TIPO_USUARIO_CHOICES)
    contacto = models.CharField(max_length=20)

    class Meta:
        db_table = 'Administracion'

Usuarios/forms.py
from django import forms
from .models import *
from django.core.exceptions import ValidationError
import re

def validar_formato_rut(rut):
    rut = re.compile(r'^\d{1,3}(?:\.\d{3}){2}\-\d|^\d{7,8}\-\d$')
    if not rut.match(rut):
        raise ValidationError('El formato del RUT es incorrecto')


class FormEstacionamiento(forms.ModelForm):
    class Meta:
        model = Estacionamiento
        fields = ['patente', 'modelo_auto','lugar', 'nombre_usuario_id', 'tipo_usuario', 'contacto']
        widgets = {
            'patente': forms.widgets.TextInput(attrs={'class': 'form-control'}),
            'modelo_auto': forms.widgets.TextInput(attrs={'class': 'form-control'}),
            'lugar': forms.widgets.TextInput(attrs={'class': 'form-control'}),
            'nombre_usuario_id': forms.widgets.TextInput(attrs={'class': 'form-control'}),
            'tipo_usuario': forms.widgets.Select(attrs={'class': 'form-control'}),
            'contacto': forms.widgets.TextInput(attrs={'class': 'form-control'}),
        }
        labels = {
            'patente': 'Patente',
            'modelo_auto': 'Modelo del Auto',
            'lugar': 'Lugar',
            'nombre_usuario_id': 'Nombre del Usuario',
            'tipo_usuario': 'Tipo de Usuario',
            'contacto': 'Contacto',
        }
        label_suffix = ''
    def clean(self):
        cleaned_data = super().clean()
        lugar = cleaned_data.get('lugar')


        if Estacionamiento.objects.filter(lugar=lugar).exists():
            self.add_error('lugar', 'Este lugar ya está ocupado')




class FormFiltroEstacionamiento(forms.Form):
    patente = forms.CharField(
        label='Buscar Patente',
        max_length=100,
        required=False,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ingrese la patente'})
    )

class FormAdministracion(forms.ModelForm):
    rut = forms.CharField(max_length=12)
    class Meta:
        model = Administracion
        fields = ['rut', 'habitacion', 'nombre_usuario_id', 'tipo_usuario', 'contacto']
        widgets = {
            'rut': forms.widgets.TextInput(attrs={'class': 'form-control'} ),
            'habitacion': forms.widgets.TextInput(attrs={'class': 'form-control'}),
            'nombre_usuario_id': forms.widgets.TextInput(attrs={'class': 'form-control'}),
            'tipo_usuario': forms.widgets.Select(attrs={'class': 'form-control'}),
            'contacto': forms.widgets.TextInput(attrs={'class': 'form-control'}),
        }
        labels = {
            'rut': 'Rut',
            'habitacion': 'Habitacion',
            'nombre_usuario_id': 'Nombre del Usuario',
            'tipo_usuario': 'Tipo de Usuario',
            'contacto': 'Contacto',
        }
        label_suffix = ''


    def clean_rut(self):
        rut = self.cleaned_data['rut']
        rut_regex = re.compile(r'^\d{6,8}-[\dkK]$')  
        if not rut_regex.match(rut):
            raise ValidationError('El formato del RUT es incorrecto')
        return rut





class FormFiltroAdministracion(forms.Form):
    rut= forms.CharField(
        label='Buscar Por Rut',
        max_length=100,
        required=False,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ingrese el rut'})
    )

class FormAdmin(forms.ModelForm):

    class Meta:
        model = Usuario
        fields = ['username', 'password', 'tipo']
        widgets = {
            'username': forms.widgets.TextInput(attrs={'class': 'form-control'}),
            'password': forms.widgets.TextInput(attrs={'class': 'form-control'}),
            'tipo': forms.widgets.Select(attrs={'class': 'form-control'}),
        }
        labels = {
            'username': 'Rut',
            'password': 'Password',
            'tipo': 'Tipo de usuario',
        }
        label_suffix = ''

    def clean_username(self):
        rut = self.cleaned_data['username']
        rut_regex = re.compile(r'^\d{6,8}-[\dkK]$')
        if not rut_regex.match(rut):
            raise ValidationError('El formato del RUT es incorrecto')
        return rut





class FormFiltroAdmin(forms.Form):
    username= forms.CharField(
        label='Buscar Persona',
        max_length=100,
        required=False,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ingrese rut'})
    )


class FormFiltroSoli(forms.Form):
    rut= forms.CharField(
        label='Cargar solicitudes',
        max_length=100,
        required=False,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ingrese rut'})
    )

templates/Signup/Datos.html
{% extends 'Base.html' %} {% block content %}
<header>
  <a href="{% url 'signup' token %}" class="btn btn-secondary">Volver al Menú Anterior</a>
  <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
  {% if messages %}
  {% for m in messages %}
      <script>
          Swal.fire({
          title: "{{m}}",

          icon: "success"
          });

      </script>
  {% endfor %}
   {% endif %}
<h1 class="mt-3 alert alert-success text-center">Lista de personas</h1>
<div class="text-end mb-3">
    <form method="post">
        {% csrf_token %}
        <div class="input-group mb-3">
            <span class="input-group-text"> Buscar rut </span> 
            {{ form.username }}    

            <input type="submit" value="Buscar" class="btn btn-success">
        </div>
    </form>
    <hr>
</div>
{%if Usuario %}
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Rut</th>
      <th>Contrasena</th>
      <th>Tipo</th>


      <th></th>
    </tr>
  </thead>
  <tbody>
    {% for p in Usuario %}
    <tr>
      <td>{{ p.username }}</td>
      <td>{{ p.password }}</td>
      <td>{{ p.tipo }}</td>
     

       <td>
           <a href="/eliminarpersonas/{{ p.username }}" class="btn btn-danger">Eliminar</a>
           <a href="/editarpersonas/{{ p.username }}" class="btn btn-warning">Editar</a>
       </td>
    </tr>
    {% endfor %}
  </tbody>
</table>

{% else %}
<div class="alert alert-warning">No existen registros</div>
</header>
{% endif %} {% endblock %}

templates/Signup/Signup.html
{% load static %}
{% block content %}

<html lang="en">
  <head>


    <!--Organizador de Header Esto permite posicionar cosas debajo del nav-->
    <style>
label[for="id_patente"],
label[for="id_modelo_auto"],
label[for="id_nombre_usuario_id"],
label[for="id_tipo_usuario"],
label[for="id_contacto"] {
    color: black;

}
    body {
    overflow-x: hidden; 
    overflow-y: hidden; 
    }
    .site-mobile-menu,
    .site-navbar {
    margin: 0;
    padding: 0;

    }


      header {
          width: 100%;
          height: 10%;
          
          padding: 250px;
      }

      nav {
          color: white;
      }

      a {
          text-decoration: none;

          border-radius: 5%;

      }

      main {
          font-size: 0px;
      }




  .contact__wrapper {
    position: relative;}
   </style>


  <!--iMPORTE ESTILOS CSS-->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700" rel="stylesheet">

    <link rel="stylesheet" href="/static/fonts/icomoon/style.css">

    <link rel="stylesheet" href="/static/css/owl.carousel.min.css">

    
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    
    
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="/static/css/formstyle.css">

    
  </head>
  <body>

<!--SIDEBAR-->
    <div class="site-mobile-menu site-navbar-target">
        <div class="site-mobile-menu-header">
          <div class="site-mobile-menu-close mt-3">

          </div>
        </div>
        <div class="site-mobile-menu-body"></div>
      </div>



      <header class="site-navbar site-navbar-target py-4 bg-dark" role="banner">




              <div class="site-logo">
                <!--NOMBRE Y LOGO-->
                <a href="/"><img src="/static/images/logo1.jpg"  width="150" height="150" href="/" ></a>

                
              </div>
            </div>

            <div class="col-9  text-right">
              




            
            </div>

            
          </div>
        </div>
    </header>
     <!--Inicio formulario-->
    <header>
        <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
        {% if messages %}
        {% for m in messages %}
            <script>
                Swal.fire({
                title: "{{m}}",

                icon: "success"
                });

            </script>
        {% endfor %}
         {% endif %}
      <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css" rel="stylesheet">
<div class="container">
    <div class="contact__wrapper shadow-lg mt-n9">
        <div class="row no-gutters">
            <div class="col-lg-5 contact-info__wrapper gradient-brand-color p-5 order-lg-2">
                <h3 class="color--white mb-5">{{ titulo2 }}</h3>


    
                        <div class="mt-3">

                        </div>
                    </li>
                </ul>
    
                <figure class="figure position-absolute m-0 opacity-06 z-index-100" style="bottom:0; right: 10px">
                    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="444px" height="626px">
                        <defs>
                            <linearGradient id="PSgrad_1" x1="0%" x2="81.915%" y1="57.358%" y2="0%">
                                <stop offset="0%" stop-color="rgb(255,255,255)" stop-opacity="1"></stop>
                                <stop offset="100%" stop-color="rgb(0,54,207)" stop-opacity="0"></stop>
                            </linearGradient>
    
                        </defs>
                        <path fill-rule="evenodd" opacity="0.302" fill="rgb(72, 155, 248)" d="M816.210,-41.714 L968.999,111.158 L-197.210,1277.998 L-349.998,1125.127 L816.210,-41.714 Z"></path>
                        <path fill="url(#PSgrad_1)" d="M816.210,-41.714 L968.999,111.158 L-197.210,1277.998 L-349.998,1125.127 L816.210,-41.714 Z"></path>
                    </svg>
                </figure>
            </div>
    
            <div class="col-lg-7 contact-form__wrapper p-5 order-lg-1">
               <form method="post">

                    <div class="row">
                        <div class="col-sm-6 mb-3">
                           
                            </form>

                            <form action="" method="post">
                                {% csrf_token %}
                                <div class="form-content">
                                    {{ form2.as_p }}
                                    <br>
                                    <input type="submit" value="Guardar" class="btn btn-primary">
                                    {% if mostrar_boton %}
                                    
                                    <a href="Datos2" class="btn btn-primary">Ver lista</a>
                                {% endif %}
                                </div>
                            </form>
                    

                  </form>

                            </div>
                        </div>
    

    

    
                    </div>
                </form>
            </div>
            <!-- Fin del formulario -->
    
        </div>
    </div>
</div>


    


  </header>

  </main>

          


<!--IMPORTE js-->
<script src="/static/js/jquery-3.3.1.min.js"></script>
<script src="/static/js/popper.min.js"></script>
<script src="/static/js/bootstrap.min.js"></script>
<script src="/static/js/jquery.sticky.js"></script>
<script src="/static/js/main.js"></script>

{% endblock %}